// src/models/product.model.js
export const mapProduct = (data) => ({
  id: data.id || 0,
  name: data.name || "",
  code: data.code || "",
  price: data.price || 0,
  priceAfterDiscount: data.priceAfterDiscount || 0,
  discount: data.discount || 0,
  description: data.description || "",
  categoryName: data.categoryName || "",
  isDelivered: data.is_deliverd || 0,
  deliveryType: data.delivery_type || "",
  feesInternal: data.fees_internal || 0,
  feesExternal: data.fees_external || 0,
  stock: data.stock || 0,
  currencyType: data.currency_type || "",
  isInstallment: data.is_installment || 0,
  status: data.status || "",
  totalRate: data.total_rate || 0,
  avgRate: data.avg_rate || 0,
  linkInsta: data.linkInsta || null,
  linkWhatsapp: data.linkWhatsapp || null,
  linkSnab: data.linkSnab || null,
  linkFacebook: data.linkFacebook || null,
  images: Array.isArray(data.image) ? data.image : [],
  isFavorite: data.is_favorite || false,
});
